"""empty message

Revision ID: 041fc7884d65
Revises: YOUR_NEW_REVISION
Create Date: 2026-08-24 13:30:13.985746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '041fc7884d65'
down_revision: Union[str, Sequence[str], None] = 'YOUR_NEW_REVISION'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credit_ledger_customer_id'), table_name='credit_ledger')
    op.drop_index(op.f('ix_credit_ledger_order_id'), table_name='credit_ledger')
    op.drop_index(op.f('ix_credit_ledger_payment_reference'), table_name='credit_ledger')
    op.drop_index(op.f('ix_credit_ledger_shop_id'), table_name='credit_ledger')
    op.drop_index(op.f('ix_credit_ledger_status'), table_name='credit_ledger')
    op.drop_index(op.f('ix_credit_ledger_transaction_type'), table_name='credit_ledger')
    op.drop_table('credit_ledger')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_ledger',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transaction_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('balance_after', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('payment_reference', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('credit_ledger_customer_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('credit_ledger_order_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('credit_ledger_shop_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('credit_ledger_pkey'))
    )
    op.create_index(op.f('ix_credit_ledger_transaction_type'), 'credit_ledger', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_credit_ledger_status'), 'credit_ledger', ['status'], unique=False)
    op.create_index(op.f('ix_credit_ledger_shop_id'), 'credit_ledger', ['shop_id'], unique=False)
    op.create_index(op.f('ix_credit_ledger_payment_reference'), 'credit_ledger', ['payment_reference'], unique=False)
    op.create_index(op.f('ix_credit_ledger_order_id'), 'credit_ledger', ['order_id'], unique=False)
    op.create_index(op.f('ix_credit_ledger_customer_id'), 'credit_ledger', ['customer_id'], unique=False)
    # ### end Alembic commands ###
