"""add cart and credit system

Revision ID: 66fa02361c49
Revises: 076e579fc34c
Create Date: 2026-08-23 18:35:41.706424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66fa02361c49'
down_revision: Union[str, Sequence[str], None] = '076e579fc34c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('customers_user_id_key'), 'customers', type_='unique')
    op.create_index(op.f('ix_customers_user_id'), 'customers', ['user_id'], unique=True)
    op.drop_constraint(op.f('customers_user_id_fkey'), 'customers', type_='foreignkey')
    op.create_foreign_key(None, 'customers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.drop_column('products', 'stock_quantity')
    op.drop_constraint(op.f('shops_address_id_fkey'), 'shops', type_='foreignkey')
    op.drop_constraint(op.f('shops_owner_user_id_fkey'), 'shops', type_='foreignkey')
    op.create_foreign_key(None, 'shops', 'addresses', ['address_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'shops', 'users', ['owner_user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shops', type_='foreignkey')
    op.drop_constraint(None, 'shops', type_='foreignkey')
    op.create_foreign_key(op.f('shops_owner_user_id_fkey'), 'shops', 'users', ['owner_user_id'], ['id'])
    op.create_foreign_key(op.f('shops_address_id_fkey'), 'shops', 'addresses', ['address_id'], ['id'])
    op.add_column('products', sa.Column('stock_quantity', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.create_foreign_key(op.f('customers_user_id_fkey'), 'customers', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_customers_user_id'), table_name='customers')
    op.create_unique_constraint(op.f('customers_user_id_key'), 'customers', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
