"""add shops table

Revision ID: e0d4cc0251af
Revises: d486f82dfce5
Create Date: 2026-08-20 13:58:26.572611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0d4cc0251af'
down_revision: Union[str, Sequence[str], None] = 'd486f82dfce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'customer_id', name='uq_shop_customer')
    )
    op.create_index(op.f('ix_shop_customers_customer_id'), 'shop_customers', ['customer_id'], unique=False)
    op.create_index(op.f('ix_shop_customers_shop_id'), 'shop_customers', ['shop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_customers_shop_id'), table_name='shop_customers')
    op.drop_index(op.f('ix_shop_customers_customer_id'), table_name='shop_customers')
    op.drop_table('shop_customers')
    # ### end Alembic commands ###
